# Generated by Django 4.0 on 2021-12-09 04:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='TextInformation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='courses.course')),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'texts',
            },
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='file_name')),
                ('file_path', models.FileField(upload_to='course_files/', verbose_name='file')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='courses.course')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'pdfs',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('link_text', models.URLField(verbose_name='link')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='courses.course')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.CreateModel(
            name='CourseUsers',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='courses.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='auth.user')),
            ],
            options={
                'verbose_name': 'course student',
                'verbose_name_plural': 'course student',
            },
        ),
        migrations.CreateModel(
            name='CourseScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка от 1 до 5')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.course', verbose_name='course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rated', to='auth.user', verbose_name='student')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(through='courses.CourseUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
